window.portfolioProjects = [
  {
    id: "luxury-hotel",
    title: "Luxury Hotel Website",
    category: "Hospitality / Premium Brand",
    description: "A modern five-star hotel website built to feel calm, premium, and simple to use. It highlights hotel information, room options, reservations, and contact details while an AI-powered guest assistant helps visitors get support fast.",
    technologies: ["next.js", "Responsive UI/UX", "AI Assistant", "Booking Flow", "Luxury Branding"],
    features: ["Hotel information hub", "Room showcase and rates", "Reservations and contact flow", "AI-powered guest support"],
    liveDemoUrl: "project-demo.html?project=luxury-hotel",
    sourceCodeUrl: null,
    image: "assets/luxury-hotel-picture.jpg",
    imageAlt: "Luxury hotel website preview",
  },
  {
    id: "textile-company",
    title: "Textile Company Website",
    category: "Corporate / Manufacturing",
    description: "A professional corporate website for a textile company with a clean product showcase and a strong company profile. The design is responsive, modern, and built to communicate credibility to B2B buyers.",
    technologies: ["React", "Corporate UI", "Responsive Design", "Brand Storytelling", "Product Showcase"],
    features: ["Company profile section", "Product showcase", "Professional corporate layout", "Modern business UI"],
    liveDemoUrl: "project-demo.html?project=textile-company",
    sourceCodeUrl: "https://github.com/behredine/kombolcha_textile_factory_web.git",
    image: "assets/textile-company-preview.jpg",
    imageAlt: "Textile company website preview",
  },
  {
    id: "educational-learning-platform",
    title: "Educational Learning Platform",
    category: "Education / Learning Product",
    description: "A learning platform organized by book chapters with written explanations, audio lectures, and embedded YouTube lessons. It is structured for students who want to read, listen, and watch in one responsive interface.",
    technologies: ["React", "Learning UX", "Media Embeds", "Responsive Design", "Content Architecture"],
    features: ["Chapter-based learning flow", "Written chapter explanations", "Audio lectures", "Embedded YouTube lectures"],
    liveDemoUrl: "https://behredine.github.io/nafais-al-muhadirat/",
    sourceCodeUrl: "https://github.com/behredine/nafais-al-muhadirat.git",
    image: "assets/educational-learning-preview.jpg",
    imageAlt: "Educational learning platform preview",
  },
];
